#  Template maven-build

#  This template allows you to test and build your Java project with Maven.
#  The workflow allows running tests, code checkstyle and security scans on the default branch.

# Prerequisites: pom.xml and appropriate project structure should exist in the repository.

image: maven:3.6.3

pipelines:
  default:
    - step:
        caches:
          - maven
        script:
          - mvn clean install -U
          - mvn clean install -DskipTests
          - mvn -Dtest=FIT_LV_REGISTERED test
          - mvn -Dtest=FIT_LV_UNREGISTERED test
          - mvn -Dtest=FIT_LV_LEAGAL test
          - mvn -Dtest=FIT_LT_REGISTERED test
          - mvn -Dtest=FIT_LT_UNREGISTERED test
          - mvn -Dtest=FIT_LT_LEAGAL test
          - mvn -Dtest=FIT_EE_REGISTERED test
          - mvn -Dtest=FIT_EE_UNREGISTERED test
          - mvn -Dtest=FIT_EE_LEAGAL test
          - mvn -Dtest=FIT_FI_REGISTERED test
          - mvn -Dtest=FIT_FI_UNREGISTERED test
          - mvn -Dtest=FIT_FI_LEAGAL test
          - mvn -Dtest=PAK_STICKER_BUY_REG test
          - mvn -Dtest=PAK_STICKER_BUY_NOT_REG test
          - mvn -Dtest=LAB_UNREG test
          - mvn -Dtest=LAB_LEAGAL test
          - mvn -Dtest=LAB_REGISTERED test
          - mvn -Dtest=LAB_REG_LEAGAL test

        after-script:
          # Collect checkstyle results, if any, and convert to Bitbucket Code Insights.
          - pipe: atlassian/checkstyle-report:0.2.0
    - step:
        name: Security Scan
        script:
          # Run a security scan for sensitive data.
          # See more security tools at https://bitbucket.org/product/features/pipelines/integrations?&category=security
          - pipe: atlassian/git-secrets-scan:0.4.3
# This is a sample build configuration for Javascript (Node.js). # Check our guides at https://confluence.atlassian.com/x/14UWN for more examples. # Only use spaces to indent your .yml configuration. # ----- # You can specify a custom docker image from Docker Hub as your build environment. image: node:4.6.0   pipelines:   default:     - step:         script: # Modify the commands below to build your repository.           - npm install           - npm test definitions:   services:     database:       image: mongo






